### ISSUE TITLE
Networks with custom subnet/mask values are not supported on this platform

### ISSUE THREAD

**Issue by axelarator** [Humoud/BackBag-Lab-VM#1]
Operating System Version: MacOS Monterey 12.4
Deploying via VMWare Fusion
Vagrant Version: 2.2.19

Description of the issue:

When attempting to bring up any VM, it errors out due to networking issues.
```
Vagrant failed to create a new VMware networking device. The following error message was generated while attempting to create a new device:
Networks with custom subnet/mask values are not supported on this platform
Please resolve any problems reported in the error message above and try again.
```

I see this is also a prevalent issue in DetectionLab as well with issue #782 and #602

**Comment by Humoud** [comment]
Thanks for bringing this to my attention. I have a mac lying around. Will see if I can find a solution or a work around.

**Comment by Humoud** [comment]
@axelarator I have some good news and bad news. Apparently, vagrant does not support setting custom IPs on VMWare Fusion on macOS Big Sur and above.

From [vagrant](https://www.vagrantup.com/docs/providers/vmware/known-issues):

"Starting with the Big Sur release VMware Fusion is no longer able to create network devices with custom subnet and mask settings to attach to guests. This means custom IP addresses are not valid when creating a private network."

Luckily we have VirtualBox supported on MacOS and I tested it! I made a new push which addresses a minor issue I faced.

I also installed the [vbguest plugin](https://github.com/dotless-de/vagrant-vbguest) on macOS:
```
vagrant plugin install vagrant-vbguest
```

Note that I did the testing on:
 - MacBook pro 2017 running macOS Catalina 10.15.7
 - Virtualbox 6.1.34 (I uninstalled VMware Fusion during testing to avoid any possible vmware related issues)
 - Vagrant 2.2.19


I am yet to update the README.md, will await feedback.

Note that the push I made mounts two folders in the project onto the Windows VMs to allow for provisioning.

**Comment by axelarator** [comment]
Ok so VirtualBox works...almost. The Windows boxes install just fine, but the Linux server gets stuck at boot. The last output in my terminal is 
`nix01: SSH auth method: private key`

Looking at the error, it appears to be a Vagrant issue rather than a BackBag issue. 
```An error occurred in the underlying SSH library that Vagrant uses. The error message is shown below. In many cases, errors from this library are caused by ssh-agent issues. Try disabling your SSH agent or removing some keys and try again.
timeout during server version negotiating.```

Now I've tried multiple steps to fix this without success.
- Incremental downgraded to vagrant 2.2.14
- Removed `~/.vagrant.d/insecure_private_key`
- `vagrant destroy` followed by `vagrant up --provider=virtualbox`
- Modified the timeout for nix01 to "1220"

**Comment by axelarator** [comment]
My bad, didn't meant to close the issue. 


Ok so VirtualBox works...almost. The Windows boxes install just fine, but the Linux server gets stuck at boot. The last output in my terminal is
nix01: SSH auth method: private key

Looking at the error, it appears to be a Vagrant issue rather than a BackBag issue.

timeout during server version negotiating.```

Now I've tried multiple steps to fix this without success.
- Incremental downgraded to vagrant 2.2.14
- Removed `~/.vagrant.d/insecure_private_key`
- `vagrant destroy` followed by `vagrant up --provider=virtualbox`
- Modified the timeout for nix01 to "1

**Comment by Humoud** [comment]
Thanks for taking the time to test, troubleshoot, and update me!

I'll test the nix box on my machine and see what I can do. Will also see if the issue will be resolved if I switch to another nix box instead of bento's.

**Comment by Humoud** [comment]
@axelarator  I faced the same exact issue and updated the Vagrantfile on the main branch with a fix.

I did the following changes under `cfg.vm.provider "virtualbox" do |v, override|`:

Added:

```
v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
``` 

Removed:

```
v.default_nic_type = "82545EM"
```

I took the configs from Detectionlab's vagrant file.

Hope it works on your end as well.

**Comment by axelarator** [comment]
Awesome, it works now. Destroyed the box, brought it back up, halted it (this failed before) and it shut down correctly. Then I brought all 4 boxes up without error.

**Comment by Humoud** [comment]
Awesome! Thanks for the feedback.
I'll close the issue now.
